<?php
namespace Mobidev\Mpesa\Facades;

use Illuminate\Support\Facades\Facade;



class Mpesa extends Facade
{
    protected static function getFacadeAccessor()
    {
        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }

}